## YAML Template.
---
services:
  registry-discovery:
    container_name: id-eureka
    image: eurekaserver_image:latest
    ports:
      - 8761:8761
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M 

  apigateway:
    container_name: id-apigateway
    image: apigateway_image:latest
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - 8079:8079

  notificacion:
    container_name: id-notificacion
    image: notificacion_image:latest
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - 8081:8081
    
  springbootadmin:
    container_name: id-springbootadmin
    image: springbootadmin_image:latest
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - 8062:8062

  user:
    container_name: bd-user
    image: user_image:latest 
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
         -CONFIG_SERVER=http://configserver:8888/
    ports:
      - 8090:8079
    depends_on:
      - registry-discovery
  
  tarea:
    container_name: bd-tarea
    image: tarea_image:latest   
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/

    depends_on:
      - registry-discovery
    ports:
      - 8082:8082
  
  keycloack:
    container_name: id-keycloackadapter
    image: keycloackadapter_image:latest
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
         -DKEYCLOACK_SERVER=http://keycloack_server:8080/realms/
         -DKEYCLOACK_REAL_ID=bdEyQBO1wGToqPgaj-tuwzn1KEGxtsnl8NUH1AgHts8
         #-Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - registry-discovery
    ports:
      - 8088:8088
      
  configserver:
    container_name: id-configserver
    image: configserver_image:latest
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - 8888:8888

  postgres_db:
      container_name: postgres
      image: postgres:latest
      ports:
        - 5432:5432
      volumes:
        - ./dbfiles:/docker-entrypoint-initdb.d
        - ./postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: qwerty
        POSTGRES_DB: usurio

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 80:80
    depends_on:
      - postgres_db
  
  keycloack_server:
    container_name: keycloackServer
    image: quay.io/keycloak/keycloak
    restart: always
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - 8091:8080




