## YAML Template.
---
server:
    port: 8079

eureka:
    client:
        serviceUrl:
            defaultzone: ${EUREKA_SERVER:http://localhost:8761/eureka}
        registerWithEureka: true
        fetchRegistry: true
        
logging:
    level:
        org.springframework.cloud.gateway: DEBUG
        reactor.netty.http.client: DEBUG

spring:
  application:
      name: apigateway
  cloud:
    gateway:
      routes:
      - id: user_check
        uri: lb://businessdomain-user
        predicates:
          - Path=/user/check
        filters:
            name: AuthenticationFiltering
          
      - id: user_service
        uri: lb://businessdomain-user
        predicates:
          - Path=/user/**
      
      - id: tarea_service
        uri: lb://businessdomain-tarea
        predicates:
          - Path=/tarea/**
          - Method=GET.POST.PUT.DELETE
        filters:
            name: AuthenticationFiltering
          
      - id: notificacion_service
        uri: lb://businessdomain-notificacion
        predicates:
          - Path=/notificacion/**
          - Method=GET.POST.PUT.DELETE 
        filters:
            name: AuthenticationFiltering
    config:
        enabled: false

